### ISSUE TITLE
Erro - unresolved reference R

### ISSUE THREAD

**Issue by gyulamester** [traccar/traccar-manager-android#102]
Erro - unresolved reference R

line 67 and 68 

 .setTitle(activity.getString(**R**.string.biometric_title))
 .setNegativeButtonText(activity.getString(**R**.string.biometric_cancel))

I can't fix this error

android studio latest
gradle 8.2.2
sdk 34

**Comment by tananaev** [comment]
If you're getting these errors, it probably means you're not using the official code.

**Comment by gyulamester** [comment]
download link > https://github.com/traccar/traccar-manager-android
