### ISSUE TITLE
Can't login: Token has expired - SecurityException

### ISSUE THREAD

**Issue by CodeShakingSheep** [traccar/traccar-manager-android#105]
**Describe the bug**
When I want to login on my Android phone, a message about an expired token is displayed.

**To Reproduce**
Try to login.

**Expected behavior**
Either I should be logged in successfully or I should have the option to renew the token.

**Screenshots**
![image](https://github.com/traccar/traccar-manager-android/assets/19874562/7cc76ddf-4fe1-4385-9b84-69e74010341c)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android 14
 - Browser: Cromite
 - Version: Latest

**Additional context**
It happens on my girlfirend's iPhone as well. So, it doesn't seem to be entirely Android related.

Edit: I could solve this on my Android phone by removing all cache and user data from the app and then specifiying my server URL again and logging in from scratch. However, there should be a more user-friendly way of handling expired tokens.

**Comment by tananaev** [comment]
I'm not able to reproduce this. Once token expires, I can login again and the new token is set.
