### ISSUE TITLE
Crash after update of Android 10 to newer Android 10

### ISSUE THREAD

**Issue by est61** [traccar/traccar-manager-android#78]
**Describe the bug**
I recently updated the phone from this version: CARBON-CR-8.0-PAX-WEEKLY-lavender-20200527-1905
to this latest version: CARBON-CR-8.0-PAX-WEEKLY-lavender-20200805-0330

After which i opened up Traccar Manager and it flashes once and crashes. Doesnt want to open.
I tried clearing data, i put in my server again with https, and as soon as i click on START, it crashes again.
I tried uninstalling and re-installing, same thing happens.

**Smartphone (please complete the following information):**
 - Device: Redmi Note 7-Lavender
 - OS: Android 10
 - Browser Firefox
 - Version: Latest from Playstore v2.10.21

**Additional context**
This never happened on other devices.
Please dont tell me its my server, as it has been working fine on other devices and for a long time now.
Also i cannot afford to rollback to the previous Android version that i had which i posted above.
Not sure what is making it crash, how can i help to debug this issue?

thank you kindly

**Comment by tananaev** [comment]
You would have to extract Android logs to see why it's crashing.

**Comment by est61** [comment]
Seems like the error was because webview had a bug on that android build
