### ISSUE TITLE
Android app cannot accept self signed certificate

### ISSUE THREAD

**Issue by lin88xu** [traccar/traccar-manager-android#79]
Hi tananaev,

I have recently downloaded the android version of traccar manager. I am having problem logging in because the app doesnt allow ssl connection using self-signed certificates, despite trusting the CA under trusted credentials. Any idea if this issue can be resolved soon? Thanks!

**Comment by tananaev** [comment]
What is the use case where you need a self signed certificate?

**Comment by lin88xu** [comment]
Well I am trying to connect to a self hosted traccar server. I cant get hold of the Lets Encrypt CA as this server is not public facing.
I found one response you had back in 2017, is this implemented already?
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>

**Comment by tananaev** [comment]
I don't think so. Feel free to send a PR.

**Comment by lin88xu** [comment]
PR created

**Comment by tananaev** [comment]
Have you checked it? PR is completely broken.

**Comment by lin88xu** [comment]
New PR created, sorry for the earlier mistake

**Comment by tananaev** [comment]
Closed this one as well. I think you don't understand what a PR is. I would recommend you to take your time are read about it.

**Comment by lin88xu** [comment]
> Closed this one as well. I think you don't understand what a PR is. I would recommend you to take your time are read about it.

Sure, will read about it first. Sorry
