### ISSUE TITLE
Traccar Manager will not work on GrapheneOS without Google components.

### ISSUE THREAD

**Issue by heybrodes** [traccar/traccar-manager-android#91]
Hello,
I want to run Traccar Manager on an Android phone running GrapheneOS.
I don't want anything "google" on my android phone so I downloaded the Traccar Manager APK directly from the traccar website.
It will install OK but it will not run without Google Play Store, Google Play Services and Google Services Framework components installed.
Is there a way around this?

**Comment by tananaev** [comment]
What's the error? Screenshot?

**Comment by heybrodes** [comment]
![image](https://user-images.githubusercontent.com/65216939/202828292-5f97651f-9cb5-4288-b898-1cce563db3a1.png)

**Comment by heybrodes** [comment]
It won't move past this screen. As sson as those components are installed it works.

**Comment by tananaev** [comment]
How is this related to Google services?

**Comment by heybrodes** [comment]
I have no idea, all I do know is that I tried to install traccar manager on 2 different GrapheneOS android phones and neither of them worked until those google components were installed. 
Having said that I have since removed those google components, removed traccar manager app and now it installs and works.
OK, all goog now.
