### ISSUE TITLE
Question: Traccar Manager used URL

### ISSUE THREAD

**Issue by nz-ngauruhoe** [traccar/traccar-manager-android#92]
Hi, I read the only way to change URL (on Android) is to clear appdata or reinstall. After changing provider and receiving new modem I have problems getting traccar going again.
About TC Manager, as per doc I first cleared app data, restarted but specifying local traccar server ip address causes "connection failed". BTW, it fails on my mobile, it works from the Windows webapp. Nothing wrong on the server side.
I then uninstalled/reinstalled and started TC manager again. To my surprise I was not presented with the screen to specify URL (as previously after clearing appdata) but directly with the server login screen.  Logging in works just fine.
My questions:
How does TC Manager know server IP address after being first 'data cleared' and subsequently uninstalled?
And secondly I need to know, to resolve my modem problems, whether it is using my local or my ddns address. How do I find out?

Thanks!

**Comment by tananaev** [comment]
For questions please use the forum instead.
