### ISSUE TITLE
User Readonly Option breaks traccar manager 

### ISSUE THREAD

**Issue by CrossFire10100** [traccar/traccar-manager-android#97]
**Describe the bug**
When I set a user to Readonly and also Device Readonly

**To Reproduce**
1. Login as admin and add a user
2. Enable "Readonly" & "Device Readonly" flags to that newly created user.
3. Login as the user from the traccar manager.
4. See error.

**Expected behavior**
Usually no error is shown on a fresh traccar manager installed from the google play store.

**Screenshots**
![Screenshot_20230418-210858](https://user-images.githubusercontent.com/50341463/232957817-212804e0-c440-4274-bef2-3613de071637.png)

**Smartphone (please complete the following information):**
 - Device: Moto Edge 20 Pro
 - OS: Android 12
 
**Additional context**
I believe the app is trying to setup the notification token and its unable, due breaking that functionality. We want to have users not touch the traccar settings and mess with notification settings and just use the app as a tracking SaaS

**Comment by tananaev** [comment]
It is because of the notification token. Fixed here: https://github.com/traccar/traccar-web/commit/bddaa24cfc1f2cfb0ce66c938528faff6c846806.
