### ISSUE TITLE
nullpointerexception after account removal from traccar manager in Android

### ISSUE THREAD

**Issue by MikeF5J** [traccar/traccar-manager-android#99]
I tried to uninstall the traccar manager app in Android and reinstall to allow me to reconfigure my server.
It kept keeping my credentials and did not ask for new server details
I then removed my account from the option in the app.
After uninstalling and re-installing it is now giving nullpointerexception after the app starts and does not go further
I have cleared the cache and app data in the android settings also. no change.

**To Reproduce**
1. Go to 'remove account'
2. Click on 'delete account'
3. Scroll down to 'save'
4. uninstall app from android
5. re-install app
6. open app

**Expected behavior**
I expeceted to be prompted with a server config when re-installing since there is no feature to change the server in the app settings after its configured once

**Screenshots**
screenshot attached.
![WhatsApp Image 2023-07-22 at 14 25 28 (1)](https://github.com/traccar/traccar-manager-android/assets/116980568/d76ac5a6-16ae-4158-b509-fb9a8ee6ab62)

**Desktop (please complete the following information):**
 no

**Smartphone (please complete the following information):**
 - Device: Samsung S21 Ultra 5G
 - OS: Android 13
 - Version UI 5.1
 - latest app from playstore and also tried direct downloading and installation of apk

**Comment by tananaev** [comment]
I'm not able to reproduce this issue. The error seems to indicate some backend issue.
